default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: king
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_magazzino_development

test:
  <<: *default
  database: rails_magazzino_test

production:
  <<: *default
  database: rails_magazzino_production